/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_glorrian_DlibInterface */

#ifndef _Included_io_github_glorrian_DlibInterface
#define _Included_io_github_glorrian_DlibInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_glorrian_DlibInterface
 * Method:    detectFaces
 * Signature: ([BII)[I
 */
JNIEXPORT jintArray JNICALL Java_io_github_glorrian_DlibInterface_detectFaces
  (JNIEnv *, jclass, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
